name: Pull Main Branch on Remote Host

on:
  push:
    branches:
      - main

jobs:
  pull-main-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7822 -t rsa server.internettools.app >> ~/.ssh/known_hosts
          echo $(ls ~/.ssh)

      - name: Check ssh keys
        run: |
          echo $(cat ~/.ssh/id_rsa)

      - name: Pull Main Branch on Remote Host
        run: |
          ssh -v -p 7822 root@server.internettools.app "cd ~/projects/vue && git pull origin main"
